import assert from "node:assert/strict";
import { generateWindowLabels, labelConflicts, normalizeWindowLabel } from "../bulk-setup.js";
assert.deepEqual(generateWindowLabels("numbered", 1), ["Window 1"]);
assert.deepEqual(generateWindowLabels("numbered", 3), ["Window 1","Window 2","Window 3"]);
assert.deepEqual(generateWindowLabels("letters", 1), ["Window A"]);
assert.deepEqual(generateWindowLabels("letters", 3), ["Window A","Window B","Window C"]);
for (const value of [0,27,1.5]) assert.throws(() => generateWindowLabels("numbered", value));
assert.throws(() => generateWindowLabels("bad", 1));
assert.deepEqual(labelConflicts([" window 1 ","B"],[{name:"Window 1"},{name:" b "}]), [" window 1 ","B"]);
console.log("Bulk setup focused tests: PASS");
for (const [a, b] of [["1", "Window 1"], ["2", "Window 2"], ["A", "Window A"], [" a ", " window a "]]) assert.equal(normalizeWindowLabel(a), normalizeWindowLabel(b));
assert.deepEqual(labelConflicts(generateWindowLabels("numbered", 3), [{name:"1"},{name:"2"}]), ["Window 1", "Window 2"]);
assert.deepEqual(labelConflicts(["Window A"], [{name:" A "}]), ["Window A"]);
console.log("Canonical legacy preview conflicts: PASS");
const numbered = [{name:"1"},{name:"Window 2"},{name:"3"}];
const lettered = [{name:"A"},{name:" window b "},{name:"C"}];
assert.deepEqual(generateWindowLabels("numbered", 2, numbered), ["Window 4","Window 5"]);
assert.deepEqual(generateWindowLabels("letters", 2, lettered), ["Window D","Window E"]);
assert.deepEqual(generateWindowLabels("letters", 3, numbered), ["Window A","Window B","Window C"]);
assert.deepEqual(generateWindowLabels("numbered", 2, lettered), ["Window 1","Window 2"]);
const retired = [{name:"Retired duplicate 99 abc"},{name:"Window Retired duplicate Z xyz"}];
assert.deepEqual(generateWindowLabels("numbered", 2, [...numbered,...retired]), ["Window 4","Window 5"]);
assert.deepEqual(generateWindowLabels("letters", 2, [...lettered,...retired]), ["Window D","Window E"]);
assert.deepEqual(generateWindowLabels("numbered", 1, [{name:"1"},{name:"5",active:false}]), ["Window 6"]);
assert.deepEqual(generateWindowLabels("letters", 1, [{name:"A"},{name:"D",active:false}]), ["Window E"]);
assert.deepEqual(generateWindowLabels("letters", 1, [{name:"Y"}]), ["Window Z"]);
assert.throws(() => generateWindowLabels("letters", 2, [{name:"Y"}]), /stop at Z/);
assert.throws(() => generateWindowLabels("letters", 1, [{name:"Z"}]), /Only 0/);
assert.throws(() => generateWindowLabels("numbered", 1, [{name:String(Number.MAX_SAFE_INTEGER)}]), /numeric limit/);
console.log("Additional-window sequencing and limits: PASS");
